---
- name: Ensure role exists in Identity directory
  uri:
    url: "https://{{ cyberark_identity_tenant }}.id.cyberark.cloud/Roles/StoreRole"
    method: POST
    headers:
      Authorization: "Bearer {{ cyberark_token }}"
    body_format: json
    body:
      Name: "{{ cyberark_group.name }}"
      Description: "{{ cyberark_group.description | default('') }}"
    status_code: [200]
    timeout: 30
    validate_certs: "{{ cyberark_validate_certs }}"
  register: _cyberark_store_role
  run_once: true
  delegate_to: localhost
  failed_when:
    - not _cyberark_store_role.json.success
    - _cyberark_store_role.json.ErrorCode | default('') != '1409'
  changed_when: _cyberark_store_role.json.success | bool
